# Generated by Django 5.2.5 on 2025-08-09 03:17

import tweet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tweet.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
